/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LicenseFrame.java
 *
 * Created on 2009-feb-20, 17:38:49
 */

package omega;

import omega.i18n.T;

/**
 * @author lars
 */
public class LicenseFrame extends javax.swing.JFrame {
    public boolean result;

    /**
     * Creates new form LicenseFrame
     */
    public LicenseFrame() {
	initComponents();
	acceptq.setText(T.t("Accept the license") + '?');
	acceptY.setText(T.t("Yes"));
	acceptN.setText(T.t("No"));
	//jTextArea1.setText("a\nbb\nccc");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jScrollPane1 = new javax.swing.JScrollPane();
	jTextArea1 = new javax.swing.JTextArea();
	acceptN = new javax.swing.JButton();
	acceptY = new javax.swing.JButton();
	acceptq = new javax.swing.JLabel();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	setAlwaysOnTop(true);
	setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

	jTextArea1.setColumns(20);
	jTextArea1.setRows(5);
	jTextArea1.setText("Licence Agreement\n\nPlease review the licence terms before installing Omega-is.\n\nCopyright (C) 2004 \"The Omega-is Group\": Heimann, Lundälv, Tjus & Nelson\nTopic Dos Hb, Meloton Hb, Tomas Tjus Psykologbyrå & SuperImpact Images Inc.\nAll rights reserved.\n\nThis software is provided 'as-is', without any express or implied warranty.\nIn no event will the authors or suppliers be held liable for any damages arising from the use of this software. \n\nWarning: This computer program is protected by copyright law and international treaties.\nUnauthorized reproduction or distribution of this program, or any portion of it,\nmay result in severe civil and criminal penalties, and will be prosecuted to the maximum extent as possible\nunder law.\n\nTitle, ownership rights, and intellectual property rights in and to the software shall remain with\n\"The Omega-is Group\".  You agree to abide by the copyright law and all other applicable including,\nbut not limited to, export control laws.  You acknowledge that the software in source code form remains\na confidential trade secret of \"The Omega-is Group\" and therefore you agree not to modify the software\nor attempt to decipher, decompile, disassemble or reverse engineer the software, except to the extent\napplicable laws specifically prohibit such restriction.\n--------------------------------------------------\n\nIf you accept all the terms of the agreement, choose \"I accept...\" to continue. \n\nYou must accept the agreement to install Omega-is.\n");
	jScrollPane1.setViewportView(jTextArea1);

	acceptN.setText("N");
	acceptN.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		acceptNActionPerformed(evt);
	    }
	});

	acceptY.setText("Y");
	acceptY.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		acceptYActionPerformed(evt);
	    }
	});

	acceptq.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
	acceptq.setText("accept");

	org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(
		layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
			.add(layout.createSequentialGroup()
				.addContainerGap()
				.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
					.add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
						.add(acceptq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 410, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(acceptY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(acceptN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
					.add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
				.addContainerGap())
	);
	layout.setVerticalGroup(
		layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
			.add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
				.addContainerGap()
				.add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
				.add(18, 18, 18)
				.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
					.add(acceptq)
					.add(acceptN)
					.add(acceptY))
				.addContainerGap())
	);

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptNActionPerformed
	// no
	result = false;
	setVisible(false);
    }//GEN-LAST:event_acceptNActionPerformed

    private void acceptYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptYActionPerformed
	// yes
	result = true;
	setVisible(false);
    }//GEN-LAST:event_acceptYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new LicenseFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptN;
    private javax.swing.JButton acceptY;
    private javax.swing.JLabel acceptq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
